[package]
name = "meadowlark"
version = "0.1.0"
authors = ["Billy Messenger <BillyDM@tutamail.com>"]
edition = "2018"
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# rusty-daw-io = { git = "https://github.com/RustyDAW/rusty-daw-io", rev = "e67441ad100ca6d629a1324835ecdc7b2ec5478e" }
rusty-daw-core = "0.7"
rusty-daw-audio-graph = { git = "https://github.com/RustyDAW/rusty-daw-audio-graph.git", rev = "898a5fee4533275406844875aa4646cd8fa987eb", features = ["cpal-backend"] }
# rusty-daw-audio-graph = { path = "../rusty-daw-audio-graph", features = ["cpal-backend"] }
cpal = "0.13"
im = "15.0"


# vizia = {path = "../vizia", features = ["meadowlark"]}
vizia = {git = "https://github.com/vizia/vizia", branch = "main", features = ["meadowlark"]}
audio-waveform-mipmap = {git = "https://github.com/RustyDAW/audio-waveform-mipmap", branch = "main"}
ringbuf = "0.2"
basedrop = "0.1"
llq = "0.1"
fnv = "1.0"
twox-hash = "1.6"
atomic_refcell = "0.1"
smallvec = "1.6"
num-traits = "0.2"
symphonia = { version = "0.3", features = ["mp3", "aac", "isomp4"] }
log = "0.4"
simple-log = "1.3.3"
image = "0.23.14"
femtovg = "0.3.0"